---
title: '0325'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


##Atomic vector

```{r}
num1 <- 5
vNum1 <- c(2, 5)
vNum2 <- c(2, num1)
#右邊num1是在call num1, 會得到5, 相當於vNum <- c(2, 5)
```

#Stacking vectors 

```{r}
vNum1 <- c(-1,5)
vNum2 <- c(2,3)
vNum3 <- c(vNum1,vNum2)
vNum4 <- c(-1,5,2,3)
vNum5 <- c(c(-1,5),c(2,3))
```

```{r}
vNumComplex <- c(c(1, 3, c(-5, 23)))
vNumComplexNotComplesAtAll <- c(1, 3, -5, 23)
```

#Vector stacking

```{r}
vNum1 <- c(-1,5)
vNum2 <- c(2,3)
vNum4 <- c() # 空向量
```


```{r}
vNum3 <- c(vNum2, vNum1)
vNum4 <- c(vNum4, vNum1) # 向量疊代 （recursive vector concatenate）
#可以發現一直重複repeat這部分,vNum4會一直在改變
```

#numeric

```{r}
num1<-5 # 非整數 -> 5.0000
num2<-5L # 整數 -> 5

num1Vector<-c(5,6,7)
num2Vector<-c(5L,6L,7L)
```

```{r}
typeof(num1Vector) #double
typeof(num2Vector) #integer
```

#Character

```{r}
char1<-"你好"
char2<-'你好'
char1Vector<-c("你好","How are you?")
```

```{r}
class(char1) #character
class(char2) #character
class(char1Vector) #character
```

他說:"今天多了一個確診。"
```{r}
HeSaid <- "他說:"今天多了一個確診。"" #wrong
```

以下兩種為讓R區隔出雙引號代表不同的意義
```{r}
HeSaid <- "他說:\"今天多了一個確診。\""
```

```{r}
HeSaid1 <- '他說:"今天多了一個確診。"'
```

```{r}
complexVector <- c("小名今年歲數", 15)
complexVector1 <- c("小名今年歲數", "15") 
```

換行
```{r}
dialogue <- c('小明說："明天不用上課。"', 
              '小花說："真的嗎？"')

cat(dialogue, sep="\n")
```


跳出commend的紀錄
(游標放在名稱上,按F1,就會出現help的用法)
```{r}
library(httr)
library(dplyr)
GET("https://api.github.com/repos/tpemartin/108-2-56-inclass-practice/commits") %>%
  content() %>%
  View()
```

```{r}
dialogue <- c("小明說：'明天不用上課。'", 
              "小花說：'真的嗎？'")

cat(dialogue, sep="\n")
```

```{r}
library(googlesheets4)
`出席狀況表單網址` <-  # 缺乏定義值
ss <- as_sheets_id(`出席狀況表單網址`)
homework_sheet <- sheets_read(ss,sheet=1)
```

```{r}
library(googlesheets4)
`出席狀況表單網址` <-  "https://docs.google.com/spreadsheets/d/1EAG49qDKPWWi0ebkVr29TLrvVnoBPfkvxYY-J3xLAHY/edit#gid=458686645"
ss <- as_sheets_id(`出席狀況表單網址`)
homework_sheet <- sheets_read(ss,sheet=1)
```

[註]
鍵號的左邊一定不能出現單引號跟雙引號，只能現在右邊，若寫在左邊就算錯
鍵號的左邊使用反頓點`

#logical

```{r}
logi1 <- c(T,TRUE,F,FALSE,FALSE)
```

加總向量內的所有元素值
```{r}
sum(logi1)
#true = 1, false = 0
```

#typeof

```{r}
num <- c(1.5, 2, 3)
int <- c(1L, 3L, -2L)
char <- c("1.5","2","3")
logi <- c(T,T,F)

typeof(num) #double
typeof(int) #integer
typeof(char) #character
typeof(logi) #logical
```

#class

```{r}
class(num) #numeric
class(int) #integer
class(char) #character
class(logi) #logical
```

##Atomic vector extended

```{r}
# 10位學生的主系
majors10_char <- c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')

typeof(majors10_char)
class(majors10_char)
```

```{r}
majors10_factor <- factor(majors10_char)
# 或
majors10_factor <- factor(
  c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')
)
#從下面level的排序可以知道,這邊factor定義社會學系=1,經濟學系=2(每台便腦的順序可能會不一樣)
typeof(majors10_factor)
class(majors10_factor)
```

```{r}
levels(majors10_factor)
```