---
title: '0401'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


##Date/Time

```{r}
browseURL("https://docs.google.com/spreadsheets/d/1EAG49qDKPWWi0ebkVr29TLrvVnoBPfkvxYY-J3xLAHY/edit#gid=458686645")
```

```{r}
library(lubridate)
```

台北 2020-03-18 13:52:40
```{r}
tpeTime <- ymd_hms("2020-03-18 13:52:40",
                   tz="Asia/Taipei")
tpeTime
```

葡萄牙 Mar.18, 2020, 05:52:40
```{r}
pgTime <- mdy_hms("Mar.18, 2020, 05:52:40",
                  tz="Europe/Lisbon")
pgTime
```

```{r}

```


##List

```{r}
vectorExample <- c(2, 6, 7)
listExample <- list(2, 6, 7)

print(vectorExample)
print(listExample)
```

每個元素值可以是不同type的物件值。
```{r}
#用vector儲存(4個值都需要相同的type)
c("2020-03-31T13:40:55Z", 
  "一芳", 
  "2", 
  "水果茶")

#用list儲存(可以依照資料有的特質，而直接用那個特質底下的type儲存)
library(lubridate) #把時間轉成電腦懂的一種date class

list(
  ymd_hms("2020-03-31T13:40:55Z"),  #Date/Time
  "一芳",  #Character
  2,  #Numeric
  "水果茶") #Character


`小明交易1` <- list(
  ymd_hms("2020-03-31T13:40:55Z"), # Date/Time class
  "一芳", # character
  2, # numeric
  "水果茶" # character
)
print(`小明交易1`)
```

物件值可以是vector形式，也可以list。
```{r}
#用vector[有5個元素]
c(
  c("108學年第1學期", "高級會計學", "高等統計學"),  #向量1
  c("108學年第2學期", "食在拉丁美洲") #向量2
)
```

```{r}
#用list(用list儲存的話會保有原來元素是向量的特性)[有2個元素]
list(
  c("108學年第1學期", "高級會計學", "高等統計學"),  #向量1
  c("108學年第2學期", "食在拉丁美洲") #向量2
)
```

```{r}
# list含兩個vectors
`小明108學年課表A` <- list(
  c("108-1","高級會計學","高等統計學"),
  c("108-2","食在拉丁美洲")
)
print(`小明108學年課表A`)
```

[註]list中若還有list, 叫做nested list(巢狀)
```{r}
# list含兩個lists
`小明108學年課表B` <- list(
  list("108-1","高級會計學","高等統計學"),
  list("108-2","食在拉丁美洲")
)
print(`小明108學年課表B`)
```

```{r}
# list含兩個lists, 子層list又各含兩個vectors
`小明108學年課表C` <- list(
  list(
    c("108-1"), # 可只寫 "108-1"
    c("高級會計學","高等統計學")
       ),
  list(
    c("108-2"),
    c("食在拉丁美洲")
  )
)
print(`小明108學年課表C`)
```

物件值可以取名。(當你覺得資料結構很複雜時)
遇到命名時，用$表示
沒有命名時，用[[2]]表示
```{r}
`小明108學年課表D` <- list(
  `上學期` = list(
    semester = c("108-1"), # 可只寫 "108-1"
    courses = c("高級會計學","高等統計學")
       ),
  list(
    semester = c("108-2"),
    courses = c("食在拉丁美洲")
  )
)
print(`小明108學年課表D`)
```


##Github Commit

```{r}
commit <- list(
  author = list(
    name = "Martin老師", 
    email = "mtlin@gm.ntpu.edu.tw",
    time = ymd_hms("2020-03-25T07:17:40Z")
  ) , #這邊不能用c(), 因為3個元素為不同的type 
  committer = list(
    name = "emilyluckey", 
    email = "emily007@gmail.com", 
    time = ymd_hms("2020-03-26T08:18:40Z")
  ), 
  message = "update"
)
print(commit)
```

跟上面其實是一樣的
```{r}
library(lubridate)
authorValues <- 
  list(
    name="Martin老師",  
    email="mtlin@gm.ntpu.edu.tw",
    time=ymd_hms("2020-03-25T07:17:40Z")
  )
committerValues <- 
  list(
    name="emilyluckey", 
    email="emily007@gmail.com",
    time=ymd_hms("2020-03-26T08:18:40Z")
  )

commit <- list(
  author=authorValues,
  committer=committerValues,
  message="update"
)

print(commit)
```

```{r}
browseURL("https://api.github.com/repos/tpemartin/108-2-56-inclass-practice/commits") 
```

```{r}
library(jsonlite) 
toJSON(commit)
```

```{r}
# 108-1 
course1_1081 <- 
  list(
    name="個體經濟學",
    teacher="Alice",
    grade=85
  )
course2_1081 <-
  list(
    name="總體經濟學",
    teacher="Mark",
    grade=78
  )
`108-1修課記錄` <- 
  list(
    course1_1081,
    course2_1081
  )

# 108-2
course1_1082 <- 
  list(
    name="作業研究",
    teacher="Jason",
    grade=90
  )
`108-2修課記錄` <- 
  list(
    course1_1082
  )

# 整合兩學期
`每學期修課記錄` <- list(
  `108-1`=`108-1修課記錄`,
  `108-2`=`108-2修課記錄`
)

# 完成記錄
`小明的修課記錄` <- 
  list(
    name="小明",
    semesters=`每學期修課記錄`
  )
print(`小明的修課記錄`)
```

```{r}

```

```{r}
library(jsonlite)
fromJSON("https://opendata.cwb.gov.tw/fileapi/v1/opendataapi/F-C0032-001?Authorization=rdec-key-123-45678-011121314&format=JSON") ->
  weather_next36hours
```

##3.7

```{r}
save(commit, listExample, `小明108學年課表D`, file = "today.Rda")
```

```{r}
load("today.Rda")
```