---
title: "0408"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##選取元素

#選「一個元素」

用位置選[[.]]
```{r}
vectorExample <- c("小明","小英","大雄")

# 有多少位置可選：
length(vectorExample)
```

```{r}
vectorExample[[1]]
vectorExample[[3]]
```

```{r}
listExample <- 
  list(
    student="小明",
    `學期`=list(
      `108-1`=list(
        list(
          name="個體經濟學",
          teacher="Alice",
          grade=85
        )
      ),
      `108-2`=list(
        list(
          name="總體經濟學",
          teacher="Mark",
          grade=78
        )
      )
    )
  )
# 有多少位置可選：
length(listExample)
```

```{r}
listExample[[1]]
listExample[[2]]
```

#臺南市運動地圖:
```{r}
library(jsonlite)
fromJSON("https://data.tainan.gov.tw/dataset/4cd9345a-04bf-4328-a97d-314ff78b4763/resource/afc025fc-1ef4-447c-b785-a680391d0ca1/download/tnsport2.json", simplifyDataFrame = F) -> tainanSportsMap

length(tainanSportsMap)
```

```{r}
tainanSportsMap[[1]]
tainanSportsMap[[1076]]
```

用名字選$.
```{r}
# 有多少名字可選：
names(listExample)
```

```{r}
listExample$student
listExample$`學期` # 特殊命名依然要用反頓點呼叫
```

顯示出原始資料
```{r}
str(listExample)
```

```{r}
listExample[["student"]]
listExample[[student]] #error
listExample$student

listExample[["學期"]] # 小心不是反頓點喔。
listExample$`學期`
```

對於已經出現在global environment中的object,才可以不需要在[[]]中加入""
```{r}
student <- "student"
listExample[[student]]
```

```{r}
fromJSON("http://data.ntpc.gov.tw/api/v1/rest/datastore/382000000A-000157-002",
         simplifyDataFrame = F) -> newTaipeiCityVaccine
```

#選「多個元素」

用位置選[c(...)]
```{r}
vectorExample
vectorExample[c(1,3)]
vectorExample[c(3,2,1)] # 產生重新排列效果
```

```{r}
# 顯示到第一層
str(listExample, max.level=1)

listExample[c(1,2)]
```

用名字選[c("name1","name2",...)]
```{r}
# 顯示到第一層
str(listExample, max.level=1)

listExample[c("學期")]
listExample[c("student","學期")]
```

臺北市夜市資料（來自臺北市食材登錄平台食材來源資訊）：
```{r}
fromJSON("https://www.dropbox.com/s/qnm9bnz7vccrvcz/taipeiNightMarkets.json?dl=1", simplifyDataFrame = F) -> taipeiNightMarkets
```

用「要/不要」邏輯向量選[c(T,T,F,...)]
```{r}
vectorExample
vectorExample[c(T,T,F)] # 要，要，不要
```

```{r}
str(listExample[c(F,T)]) # 不要，要
str(listExample[c(T,T)]) # 要，要
```

```{r}
str(listExample)
```

```{r}
get1 <- listExample[["學期"]]
get2 <- listExample["學期"]
```

```{r}
get1 # 學期拿出來，有3個元素的list
str(get1)
```

```{r}
get2 # listExample 只留下 學期元素，是個只有一個元素的list
str(get2)
```

#連鎖選取

```{r}
numVector <- c(2,3,6,-1,4,2,6)
select1 <- numVector[c(1,4)]; select1
select2 <- select1[[1]]; select2

# 相當於
numVector[c(1,4)][[1]]
```

```{r}
select1 <- numVector[c(T,T,F,T,F,F,T)]; select1
select2 <- select1[c(1,4)]; select2

# 相當於
numVector[c(T,T,F,T,F,F,T)][c(1,4)]
```

```{r}
majors <- c("經濟學系","經濟學系","社會學系","社工系","經濟學系")
names <- c("小英", "小美", "大雄","阿華", "阿尼")
gender <- c("F","F","M","F","M")
```

```{r}
today <- list(
  list("台北市",c(highest_temp = 25),c(lowest_temp = 18)),
  list("新北市",c(highest_temp = 24),c(lowest_temp = 15)))
tomorrow <- list(
  list("台北市",c(highest_temp = 25),c(lowest_temp = 18)),
  list("新北市",c(highest_temp = 24),c(lowest_temp = 15)))

weather <- list(today,tomorrow)

print(weather)
```

```{r}
weather[[1]][[2]][[2]] # 今天/新北市/highest_temp
weather[[2]][[2]][[2]] # 明天/新北市/highest_temp
```

```{r}
weather[[1]][[2]]$highest_temp # 今天/新北市/highest_temp
weather[[2]][[2]]$highest_temp # 明天/新北市/highest_temp
```

#list補充

```{r}
library(jsonlite)
fromJSON("https://www.dropbox.com/s/6252gbdnv9owljm/dance.json?dl=1", simplifyDataFrame = F) -> dance
```

```{r}
fromJSON("https://cloud.culture.tw/frontsite/trans/SearchShowAction.do?method=doFindTypeJ&category=3", simplifyDataFrame = F) -> dance
```

```{r}
# 前三筆演出的名稱
dance[[1]]$title
dance[[2]]$title
dance[[3]]$title 
```

```{r}

```

```{r}

```












