---
title: '0415'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
str(listExample)
```

#[[]]及[]的差別
```{r}
get1 <- listExample[["學期"]] #拿出來
get1 <- listExample$`學期` #拿出來

get2 <- listExample["學期"] #只留下
```

#從get1取出
```{r}
get1 <- listExample[["學期"]]
get1$`108-1` -> get1_layer1
get1_layer1[[1]] -> get1_layer2
get1_layer2$teacher
```

```{r}
get1$`108-1`[[1]]$teacher
```

#從get2取出
```{r}
get2 <- listExample["學期"]
get2_layer1 <- get2[[1]]
get2_layer2 <- get2_layer1[["108-1"]]
get2_layer3 <- get2_layer2[[1]]
get2_layer3$teacher
```

```{r}
get2[[1]][["108-1"]][[1]]$teacher
```

```{r}
listExample["學期"][[1]][["108-1"]][[1]]$teacher
listExample["學期"][["學期"]][["108-1"]][[1]]$teacher
```

list多了一個$的取法
atomic vector不能用$取
```{r}
vector1 <- c(a = 1, b = 3, c = 4)
vector1[["a"]]
vector1[c("a", "c")]
vector1$a #error

vector2 <- list(a = 1, b = 3, c = 4)
vector2[["a"]]
vector2[c("a", "c")]
vector2$a
```

今明兩日台北市、新北市氣溫：
```{r}
today <- list(
  list("台北市",c(highest_temp = 25),c(lowest_temp = 18)),
  list("新北市",c(highest_temp = 24),c(lowest_temp = 15)))
tomorrow <- list(
  list("台北市",c(highest_temp = 25),c(lowest_temp = 18)),
  list("新北市",c(highest_temp = 24),c(lowest_temp = 15)))

weather <- list(today,tomorrow)

print(weather)
```

```{r}
weather[[1]][[2]][[2]] # 今天/新北市/highest_temp
weather[[2]][[2]][[2]] # 明天/新北市/highest_temp
```

$只能用在list的名稱
此處是放在c()裡面，所以行不通
```{r}
weather[[1]][[2]]$highest_temp # 今天/新北市/highest_temp
weather[[2]][[2]]$highest_temp # 明天/新北市/highest_temp
```

```{r}
library(jsonlite)
fromJSON("https://www.dropbox.com/s/6252gbdnv9owljm/dance.json?dl=1", simplifyDataFrame = F) -> dance
```

```{r}
# 前三筆演出的名稱
dance[[1]]$title
dance[[2]]$title
dance[[3]]$title 
```

將所有的title都放在dance_title裡面
```{r}
library(purrr)
map(dance,~.x$title) -> dance_title
```

```{r}
dance[[1]]$showInfo
length(dance[[1]]$showInfo)

dance[[2]]$showInfo
length(dance[[1]]$showInfo)
```

```{r}
length(dance[[1]]$showInfo)
length(dance[[2]]$showInfo)
# :
length(dance[[34]]$showInfo)
```

```{r}
map(dance,~length(.x$showInfo)) -> dance_showInfoLength
```

新北市公車路線清單
```{r}
library(jsonlite)
fromJSON("https://data.ntpc.gov.tw/od/data/api/67BB3C2B-E7D1-43A7-B872-61B2F082E11B?$format=json", simplifyDataFrame = F) ->
  busRoutes
```

##新增/替換/刪除元素

元素提取[.],[[.]],$.也可用來進行元素「值」的修改與新增, 使用方法為：

obj[.] <- value
obj[[.]] <- value
obj$. <- value

若.所指定的元素不存在，則為「新增」。

若.所指定的元素存在，則為「修改」。

```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在: 替換
a[[4]] <- "7" # 元素不存在： 增加
a[c(5,6)] <- c("J", "K")
a

a[[7]] <- "Johnson"
a

a <- c(a, c("Mary"))
a
```

```{r}
library(lubridate)
list1 <- 
  list(
    list(
      name="Jack",
      birthday=ymd("1998-03-21"),
      status=c(height=177, weight=80)
    )
  )

str(list1)
```

```{r}
library(lubridate)
# 更改日期
list1[[1]]$birthday <- ymd("1997-03-21")

# 新增資料
list1[[2]] <- list(
  name="Mary",
  birthday=ymd("1998-08-24")
)

str(list1)
```

```{r}
list1[[2]]$status <- c(height=163, weight=45)
list1[[1]]$status[["height"]] <- 176
str(list1)
```

```{r}
list1[[1]][["age"]] <- 21
list1[[2]]["age"] <- list(21) #如果前面是[]，箭頭右邊要加上他母層的結構

# 改變「一個」時，使用[[ ]]比較不會錯。
str(list1)
```

```{r}
list1[[1]][c("bloodType","registered")] <- list("AB",TRUE)

str(list1)
```

```{r}
listExample <- 
  list(
    student="小明",
    `學期`=list(
      `108-1`=list(
        list(
          name="個體經濟學",
          teacher="Alice",
          grade=85
        )
      ),
      `108-2`=list(
        list(
          name="總體經濟學",
          teacher="Mark",
          grade=78
        )
      )
    )
  )
# 有多少位置可選：
length(listExample)
```

```{r}
str(listExample)

# 108-1新增一科目成績
listExample$學期$`108-1`[[2]] <-
  list(name="產業經濟學")
str(listExample)

listExample$學期$`108-1`[[2]][c("teacher","grade")] <- 
  list(
    "Wen",
    88
    )
str(listExample)
```

#刪除可以使用[- c(數字位置)]

只能「一個」中括號（[[.]]不能接受負數值）
只能用負數值，不能用元素名稱。
```{r}
print(a)
a[-c(1,3)]
a[c(-2)]

print(a)
a[-c(1,3)] -> a # 要回存才算真的刪除
```

```{r}
library(lubridate)
list1 <- 
  list(
    list(
      name="Jack",
      birthday=ymd("1998-03-21"),
      status=c(height=177, weight=80)
    ),
    list(
      name="Mary",
      birthday=ymd("1998-08-24"),
      status=c(height=163, weight=45),
      age=21,
      bloodType="AB"
    )
  )
str(list1)
```

```{r}
str(list1)
list1[[1]][-3] -> list1[[1]] # 小心回存的位置
#回存的位置是改變的那一層，不能存到整個list1

list1[[2]][-c(4,5)] -> list1[[2]]
```

```{r}
str(list1)
list1[[2]][c(1,2)] <- NULL
str(list1)
```

```{r}
library(jsonlite)
fromJSON("https://data.ntpc.gov.tw/od/data/api/54DDDC93-589C-4858-9C95-18B2046CC1FC?$format=json", simplifyDataFrame = F) -> newTaipeiYouBike
```

```{r}
library(jsonlite)
fromJSON("https://api.github.com/repos/tpemartin/108-2-56-inclass-practice/commits", simplifyDataFrame = F) -> githubCommit
```

```{r}
githubCommit[[3]][["commit"]][["committer"]][-c(2)] -> 
  githubCommit[[3]][["commit"]][["committer"]]
githubCommit[[3]][["commit"]][["committer"]]
```

```{r}
githubCommit[[2]][["commit"]][["committer"]][c(2)] <- NULL
githubCommit[[2]][["commit"]][["committer"]]
```

```{r}
githubCommit[[1]][["commit"]][["committer"]]
```

