---
title: '0506'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
example <- list(
  name=c("小明","小花","小新","美美"),
  height=c(175,166,170,160),
  weight=c(77,NA,60,43),
  birthday=lubridate::ymd(c("1998-03-11","1999-12-22","1995-08-22","2001-10-10")),
  hobby=c("美食 旅遊","旅遊 時尚","3C 美食","音樂 旅遊"),
  residence=c("Taipei","New Taipei","Taichung","Kaohsiung"),
  allowance=factor(c("0-1000","1001-2000","2000+","1001-2000")),
  bloodType=c("A","B","B","O")
)
```

##On logical class

邏輯向量間（即「要/不要」向量）的操作主要是以下幾個：
&: AND
|: OR

```{r}
str(example)
pick_above170 <- example$height >= 170
pick_bloodB <- example$bloodType == "B"
pick_loveFood <- 
  stringr::str_detect(example$hobby,"美食")
pick_na <- is.na(example$weight)
pick_after98 <- 
  example$birthday >= lubridate::ymd("1998-01-01")
set_TaipeiMetro <- c("Taipei","New Taipei")
pick_fromTaipeiMetro <- 
  example$residence %in% set_TaipeiMetro
```

誰喜歡美食且血型為B型
```{r}
str(example[c("name","hobby","bloodType")])

example$name[
    pick_loveFood & pick_bloodB
  ]
```

誰1998以後（含）出生或不住大台北
```{r}
example[c("name","birthday","residence")]

example$name[
  pick_after98 | !pick_fromTaipeiMetro
]
```

誰1998以後（含）出生且住大台北且血型B型
```{r}
example$name[
  pick_after98 & pick_fromTaipeiMetro & pick_bloodB
]
```


##On character class

```{r}
library(stringr)
library(glue)
```

學號“410873002”，其中108是入學年，73是學系碼。 對100學年以後學生學系碼是固定在「第5、6位元」。
```{r}
str_sub("410873002", 5, 6)

str_sub(c("410873002", "410652001"), 5, 6)
```

如何讀入“民國108年12月5日”、“民國98年10月5日”?
```{r}
lubridate::ymd(
  c("民國108年12月5日","民國98年10月5日")
)
#lubridate對年只有西元年的概念。
```

lubridate裡的字串日期時間判斷採取的策略是「忽略非數字文字」只以「數字組合」（還允許各地習慣使用的文字，如March, Mar都是3月的意思）判斷時間，所以以下幾個都可以產生「西元」“2019-12-05”:
```{r}
lubridate::ymd(
  c(
    "民國2019年12月05日",
    "馬丁2019的12課05muydifícil",
    "助教2019Emily12解說05真棒",
    "2019R12課程05すごい",
    "R程式2019的12期中考05とても変態"
  )
)
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```




