---
title: '0602'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# p=1.2的需求量
p=1.2
qd <- 10-5*p # 小心是5*p, 不能寫5p
# p=1.3的需求量
p=1.3
qd <- 10-5*p
# p=1.4的需求量
p=1.4
qd <- 10-5*p
```

```{r}
demand <- # 創造一個物件叫demand
  function(p){ # 定義這個物件為函數
    q_d <- 10-5*p # 小心是5*p, 不能寫5p
  }
```

```{r}
p
qd
demand
demand()
demand(p=1.2)
demand(1.2)
```

```{r}
# p=1.2的需求量
demand(1.2) 
# p=1.3的需求量
demand(1.3)
# p=1.4的需求量
demand(1.4)
```

每一個function只能return一個物件，如果要return多個的時候，可以用list包起來。
```{r}
demand_return <- 
  function(p){
    q_d <- 10-5*p
    return(q_d)
  }
# 印在螢幕，但Global Environment並不會有q_d
demand_return(1.2)

demand(1.2)
demand_return(1.2)
```

最近一步會使用到電腦記憶體的運算值會暫時記在：
```{r}
.Last.value

2-5
.Last.value

# 要長久存在Global Environment要指定物件名稱（不要求與q_d同名）
demand_return(1.2) -> q_d1.2
```

當function有return時,
```{r}
demand_return(1.2) # 相當於
4

demand_return(1.2) -> q_d1.2 # 相當於
4 -> q_d1.2
```

```{r}
#自行先設定
q_d <- 5

#問機器人的結果
demand_return(p=1.2)
print(q_d)

#雖然同樣會產生一個q_d，但機器人想的只會return他所想的值，不會影響到在environment所設定的相同的q_d的值
```

```{r}
library(lubridate)
dateInput <- today()
locationInput <- "新北市"

jsonlite::fromJSON("https://opendata.cwb.gov.tw/fileapi/v1/opendataapi/F-C0032-001?Authorization=rdec-key-123-45678-011121314&format=JSON") ->
  weather_next36hours

# 找出符合地點的天氣資訊：weatherAtLocation
(weather_next36hours$cwbopendata$dataset$location$locationName == locationInput) -> pick_location # 可挑出locationInput的「要/不要」向量

weather_next36hours$cwbopendata$dataset$location$weatherElement[pick_location][[1]] -> weatherAtLocation

# 在weatherAtLocation找出符合時間的天氣資訊

(weatherAtLocation$elementName=="MaxT") ->
  pick_MaxT
(weatherAtLocation$elementName=="MinT") ->
  pick_MinT
weatherAtLocation$time[pick_MaxT][[1]]$parameter$parameterName[[1]] -> maxT
weatherAtLocation$time[pick_MinT][[1]]$parameter$parameterName[[1]] -> minT

glue::glue("{locationInput} {dateInput} 氣溫，最高{maxT}度，最低{minT}度。")
```

打造Silly天氣預報機器人：
```{r}
askSilly_weather <- function(locationInput,dateInput){
  jsonlite::fromJSON("https://opendata.cwb.gov.tw/fileapi/v1/opendataapi/F-C0032-001?Authorization=rdec-key-123-45678-011121314&format=JSON") ->
  weather_next36hours
  
  (weather_next36hours$cwbopendata$dataset$location$locationName == locationInput) -> pick_location
  
  weather_next36hours$cwbopendata$dataset$location$weatherElement[pick_location][[1]] -> weatherAtLocation
  (weatherAtLocation$elementName=="MaxT") ->
    pick_MaxT
  (weatherAtLocation$elementName=="MinT") ->
    pick_MinT
  weatherAtLocation$time[pick_MaxT][[1]]$parameter$parameterName[[1]] -> maxT
  weatherAtLocation$time[pick_MinT][[1]]$parameter$parameterName[[1]] -> minT
  
  glue::glue("{locationInput} {dateInput} 氣溫，最高{maxT}度，最低{minT}度。")
}



askSilly_weather("臺中市",today())
askSilly_weather("花蓮縣",today())
```

打造一個國際時間轉換機器人叫what_time_it_is
```{r}
what_time_it_is<-function(timezone){
now<-with_tz(now(),tz=timezone)
return(now)
}



what_time_it_is("Europe/Paris")
```

```{r}
class(demand_return)

# 查詢函數formals arguments要求
formals(askSilly_weather)

# 查詢函數主體
body(askSilly_weather)
```

函數可以存在list裡
```{r}
learning_topics <- 
  list(
    subject="函數",
    date=lubridate::ymd("2020-06-03"),
    functionsCreated=list(
      demand=demand_return # 等號右邊是呼叫demand_return的定義值，也就是function(...){...}值定義本身。
    )
  )



learning_topics$functionsCreated$demand(1.2)

rm(demand_return)
learning_topics$functionsCreated$demand(1.2)
#就算將environment中的demand_return拿掉，仍然可以從list中把它叫出來
```

```{r}
#再把demand_return存回environment
demand_return <- 
  function(p){
    q_d <- 10-5*p
    return(q_d)
  }

typeof(demand_return)
class(demand_return)

# 查詢函數執行所要求環境
environment(demand_return)

# 若函數執行需要Global environment已存在某些物件，查詢需要哪些物件
codetools::findGlobals(demand_return)
```

```{r}
intercept <- 10
slope <- -5
myDemand <- function(p){
  q_d <- intercept + slope*p
  return(q_d)
}

environment(demand_return)
environment(myDemand)

codetools::findGlobals(demand_return)
codetools::findGlobals(myDemand) 
# myDemand對Global environment的要求多了intercept及slope

# 移除global environment裡的intercept及slope
rm(intercept, slope)

demand_return(1.2) # 維持正常運作

myDemand(1.2) # 無法運作

#將intercept以及slope重新定義，即可成功執行myDemand
intercept <- 10
slope <- -5
myDemand(1.2)
```

Lazy evaluation
若重新定義intercept或slope，會造成myDemand()的值改變
```{r}
intercept <- 10
slope <- -5
myDemand(1.2)

slope <- -1
myDemand(1.2)

intercept <- 5
slope <- -1.2
myDemand(1.2)
```

預設值
```{r}
myDemand2 <- function(p, intercept=10, slope=-5){
  q_d <- intercept + slope*p
  return(q_d)
}

environment(myDemand2)
codetools::findGlobals(myDemand)
codetools::findGlobals(myDemand2) # 不依靠global env裡的intercept/slope

rm(intercept)
rm(slope)

myDemand2(1.2) #使用預設值的情況下
myDemand2(1.2, slope=-1)
myDemand2(1.2, intercept=5, slope=-1.2)
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```
